services:
  - type: web
    name: student-sentiment-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /api/ping
    autoDeploy: true
